# Generated by Django 4.2.30 on 2026-06-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_attendance_id_alter_profile_id'),
        ('accounts', '0010_alter_profile_points_alter_profile_worry_count'),
    ]

    operations = [
    ]
