# Generated by Django 4.2.30 on 2026-06-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20260624_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useryang',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
