# Generated by Django 6.0.5 on 2026-06-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0008_alter_epilogue_id_alter_pointlog_id"),
        ("writers", "0008_alter_epilogue_worry"),
    ]

    operations = []
