# Generated by Django 6.0.5 on 2026-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writers", "0009_merge_20260624_0911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="epilogue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pointlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
